
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.sysbind.io
  resources:
  - runtimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.sysbind.io
  resources:
  - runtimes/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.sysbind.io
  resources:
  - runtimes/status
  verbs:
  - get
  - patch
  - update
